### ISSUE TITLE
Next CamillaDSP version allows more ways to define filters

### ISSUE THREAD

**Issue by HEnquist** [HEnquist/camillagui#46]
Peaking/Allpass/Notch/Bandpass will allow giving either `bandwidth` or `q`, and High/Lowshelf will allow either `slope` or `q`. 
The question is how to implement this in the gui. Simplest is probably a dropdown to select which definition is used. Other ideas?  

Example definitions, both valid:
```
peak_100_q:
    type: Biquad
    parameters:
      type: Peaking
      freq: 100
      q: 0.5
      gain: -5.0
  peak_100_bw:
    type: Biquad
    parameters:
      type: Peaking
      freq: 100
      bandwidth: 0.7
      gain: -5.0

```
